### PR TITLE
CLI tool

### PR DESCRIPTION
**Pull request by IonicaBizau**
This is a minimal start where to start the cli interface.

### CODE REVIEW

**Comment by SpaceG** [comment]
now it's the same before.. without the cli.js 
and when I'm going with sudo gitlist 
i get this 

Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ sudo gitlist
: command not foundist: line 1: 
: No such file or directorye 2: /**
: command not foundist: line 3: 
: command not foundist: line 4: 
/usr/local/bin/gitlist: line 5: app.js: command not found
debug: --------------------------------------------------------
debug: :: Mon May 02 2016 09:11:49 GMT+0200 (CEST)
debug: Environment : development
debug: Port        : 80
debug: --------------------------------------------------------

**Comment by IonicaBizau** [comment]
You have to `npm link`.

**Comment by SpaceG** [comment]
okey, i have done this all, but i get alot of errors back and i dont know... 

Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ npm link 
gitlist@1.0.2 /Users/cyberspace/Documents/Apps/www.gitlist.io/gitlist.io/gitlist Kopie 5.io
└─┬ tilda@4.2.1 
  ├── ansi-parser@3.2.2 
  ├── arrs-to-obj@1.0.1 
  ├─┬ clp@4.0.1 
  │ ├── last-char@1.3.2 
  │ └── match-it@1.0.1 
  ├── deffy@2.2.2 
  ├─┬ err@2.1.1 
  │ └─┬ barbe@2.2.1 
  │   └── regex-escape@3.4.1 
  ├── indento@1.1.2 
  ├── is-empty-obj@1.0.3 
  ├── is-undefined@1.0.1 
  ├── iterate-object@1.3.2 
  ├─┬ le-table@6.1.1 
  │ ├─┬ cli-box@6.0.1 
  │ │ └── is-win@1.0.1 
  │ └─┬ overlap@2.2.2 
  │   ├── ansi-parser@3.0.0 
  │   ├─┬ cli-box@5.0.0 
  │   │ └─┬ ul@5.0.0 
  │   │   ├── deffy@2.0.0 
  │   │   └── typpy@2.0.0 
  │   └─┬ couleurs@5.0.0 
  │     ├── flat-colors@3.0.0 
  │     ├── typpy@2.0.0 
  │     └── x256@0.0.2 
  ├── r-json@1.2.2 
  ├── remove-blank-lines@1.0.1 
  ├── typpy@2.3.2 
  ├─┬ ul@5.2.2 
  │ ├── deffy@2.0.0 
  │ └── typpy@2.0.0 
  └── wrap-text@1.0.1 

npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
npm ERR! gentlyRm /usr/local/lib/node_modules/gitlist/app.js symlink target /usr/local/bin/gitlist is not controlled by npm /Users/cyberspace/Documents/Apps/www.gitlist.io/gitlist.io/gitlist Kopie 5.io
npm ERR! Darwin 14.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "link"
npm ERR! node v0.12.7
npm ERR! npm  v3.3.9
npm ERR! path /usr/local/bin/gitlist
npm ERR! code EEXIST

npm ERR! Refusing to delete: /usr/local/bin/gitlist not in /Users/cyberspace/Documents/Apps/www.gitlist.io/gitlist.io/gitlist Kopie 5.io
File exists: /usr/local/bin/gitlist
Move it away, and try again. 

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cyberspace/Documents/Apps/www.gitlist.io/gitlist.io/gitlist Kopie 5.io/npm-debug.log
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$

**Comment by IonicaBizau** [comment]
Who created `/usr/local/bin/gitlist`? You'll have to delete it.

**Comment by SpaceG** [comment]
where?

**Comment by SpaceG** [comment]
how to remove it via commandline.? i get this out...
I'm tired of this shit. 

Space-Odysseys-Mac-Pro:~ cyberspace$ sudo cd /usr/local/bin/gitlist
/usr/bin/cd: line 4: cd: /usr/local/bin/gitlist: Not a directory
Space-Odysseys-Mac-Pro:~ cyberspace$

**Comment by IonicaBizau** [comment]
` sudo mv /usr/local/bin/gitlist ~/gitlist.backup` to move it in your home directory (just in case you have some stuff in there)

**Comment by SpaceG** [comment]
finally found on <code> cd /usr/local/bin</code>  crazy.. this here with mac...

**Comment by SpaceG** [comment]
after this : nothing works anymore.. my command not found the app.. or whatever 

Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ sudo gitlist
sudo: gitlist: command not found
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$

**Comment by SpaceG** [comment]
now i get this after <code>npm link</code> 

Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ sudo npm link
npm WARN EPEERINVALID mongodb-core@1.2.31 requires a peer of kerberos@~0.0 but none was installed.
/usr/local/bin/gitlist -> /usr/local/lib/node_modules/gitlist/cli.js
/usr/local/lib/node_modules/gitlist -> /Users/cyberspace/Documents/Apps/www.gitlist.io/gitlist.io/gitlist Kopie 5.io
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ sudo gitlist
/Users/cyberspace/Documents/Apps/www.gitlist.io/gitlist.io/gitlist Kopie 5.io/cli.js:5
const Tilda = require("tilda")
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$

**Comment by IonicaBizau** [comment]
You'll have to update your node version to `>=4.0.0`. You can check it using `node --version`.

**Comment by SpaceG** [comment]
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ node -v
v0.12.7

**Comment by SpaceG** [comment]
how to update it via commandline.?

**Comment by IonicaBizau** [comment]
via nvm https://github.com/creationix/nvm#install-script

**Comment by SpaceG** [comment]
ufff.. Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ sudo gitlist
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$  

nothing happend...

and now when i lift the app with normal 
$ sudo sails lift

nothing works 

bindings errors etc.

**Comment by IonicaBizau** [comment]
Run `gitlist --help`.

**Comment by SpaceG** [comment]
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ gitlist --help
Usage: gitlist <command> [options]

Gitlist OS

Commands:
  start  Starts the app.
                        
Options:
  -v, --version  Displays version information.
  -h, --help     Displays this help.          
                                              
Documentation can be found at https://github.com/SpaceG/gitlist.io#readme.
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ start
-bash: start: command not found
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ Starts the app
-bash: Starts: command not found
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ start
-bash: start: command not found
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ sudo start
sudo: start: command not found
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ Gitlist OS 
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$

**Comment by SpaceG** [comment]
which is the command?

**Comment by IonicaBizau** [comment]
Well, the thing is you have to look in the `cli.js` file and write your stuff there: https://github.com/SpaceG/gitlist.io/blob/852aa63de88d1f7274847cfa0433dbf0ccf28462/cli.js#L5-L16

**Comment by SpaceG** [comment]
need i have to change the name to <code> gitlist</code>?

parser.action({
 <code>   name: "start"</code> 
  , desc: "Starts the app."
});

parser.on("start", action => {
    console.log("Start");
});

**Comment by IonicaBizau** [comment]
Check out the [Tilda docs](https://github.com/IonicaBizau/tilda).

**Comment by SpaceG** [comment]
but app does not lift...

**Comment by SpaceG** [comment]
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$ gitlist
Start
Space-Odysseys-Mac-Pro:gitlist Kopie 5.io cyberspace$

**Comment by SpaceG** [comment]
it's not possible to run this app with a own commandline... ?

**Comment by SpaceG** [comment]
i dont know.. but the app does not lift... after start it stop i can0t see the app at the localhost... 
maybe do you have missunderstod me... 

should i make it back.?

**Comment by IonicaBizau** [comment]
@SpaceG Well, you have to implement the functionality in `cli.js`.

**Comment by SpaceG** [comment]
ok, i can't do that...

**Comment by SpaceG** [comment]
even i dont knwo what teh script doing.. how it works and for what it is... ! -

**Comment by SpaceG** [comment]
sudo gitlost ... ;)!

**Comment by SpaceG** [comment]
anyway...

**Comment by IonicaBizau** [comment]
I'm not sure what happened. In `cli.js` it's a prototype how to start building the cli functionality. Of course, you have to write the actual implementation of what you want to build.

**Comment by SpaceG** [comment]
lift the app.. but anyway.. for this.. I'm too old to hanging out for hours for this shit.. and in the end works nothing..e verytime time same one.. ! -

**Comment by SpaceG** [comment]
okey i will tried it today eve ! hope thats okey :(

Am Montag, 2. Mai 2016 schrieb Ionică Bizău :

**Comment by SpaceG** [comment]
found this one :   [http://stackoverflow.com/questions/5818202/how-to-run-node-js-app-forever-when-console-is-closed](http://stackoverflow.com/questions/5818202/how-to-run-node-js-app-forever-when-console-is-closed)

**Comment by SpaceG** [comment]
here ?
where to put this in.? in the app.js ? 
<pre>

var http = require("http");
http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  console.log("welcome world")
  response.end();
}).listen(9000,"127.0.0.1");

</pre>

**Comment by SpaceG** [comment]
Hey, 

i got some infos. : http://sailsjs.org/documentation/concepts/programmatic-usage
and i have to check... first time to built a commandline in node.js  .- tell me what are you think which the best way.. for to get it. ? 👍

**Comment by spacegits** [comment]
but i dont can fix it. :

because :




#!/usr/bin/env node



"use strict";

const Tilda = require("tilda")

let parser = new Tilda(`${__dirname}/package.json`)

parser.action({
    name: "gitlist"
  , desc: "Starts the app."
});

parser.on("gitlist", action => {
    console.log("Start The Gitlist App");
});



var http = require("http");
http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  console.log("welcome world! Welcome to the Gitlist OS")
  response.end();
}).listen(80,"127.0.0.1");




it make a new blank localhost with a „helloworld!“ but i want lift my app 

whjat is wrong ?
are you have a idea? …
how to make it 

1. that the cli.js loads direct the app ? 

2. second way? need i have to take a path there like (“./app.js“) or so.? 


please can you help with this.== then i can finish it today.
i dont know what to implement into the cli.js file…


that’s the idea… this is why i have pushed this gitlist to the open source.
learning by doing.. I’m not so fit these parts… 


let me know and wish you a nice day.
Lucas

**Comment by SpaceG** [comment]
#!/usr/bin/env node



"use strict";

const Tilda = require("tilda")

let parser = new Tilda(`${__dirname}/package.json`)

parser.action({
    name: "gitlist"
  , desc: "Starts the app."
});

parser.on("gitlist", action => {
    console.log("Start The Gitlist App");
});



var http = require("http");
http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  console.log("welcome world! Welcome to the Gitlist OS")
  response.end();
}).listen(80,"127.0.0.1");

**Comment by SpaceG** [comment]
https://www.smashingmagazine.com/2014/02/build-cli-tool-nodejs-phantomjs/ 
the Phantom one looks very easy. 🎱 

#!/usr/bin/env node

"use strict";

const Tilda = require("tilda")

let parser = new Tilda(${__dirname}/package.json)

parser.action({
name: "gitlist"
, desc: "Starts the app."
});

parser.on("gitlist", action => {
console.log("Start The Gitlist App");
});

var http = require("http");
http.createServer(function(request, response) {
response.writeHead(200, {"Content-Type": "text/plain"});
response.write("Hello World");
console.log("welcome world! Welcome to the Gitlist OS")
response.end();
}).listen(80,"127.0.0.1");

**Comment by IonicaBizau** [comment]
@SpaceG You have to put your code [here](https://github.com/SpaceG/gitlist.io/blob/master/cli.js#L52).

Change `gitlist` into `lift`, [here](https://github.com/SpaceG/gitlist.io/blob/master/cli.js#L42). When you will run `gitlist lift`, the code from that callback will be executed.

I'm not sure how `sails` work, because I didn't work with it.

**Comment by SpaceG** [comment]
okey, i will have a look at this : 
now at npm publish i will get this back : 
maybe i have to go with <code> sudo npm publish</code> 
its look like on /usr/local/ 


and this ?<code> npm ERR! Remove the 'private' field from the package.json to publish it. </code> ?

the <code> npm ERR!     /Users/cyberspace/Documents/gitlist.io/npm-debug.log </code> i have removed but it come back everytime again : ? :D  


<pre>
Space-Odysseys-Mac-Pro:gitlist.io cyberspace$ npm publish
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1

npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cyberspace/Documents/gitlist.io/npm-debug.log
Space-Odysseys-Mac-Pro:gitlist.io cyberspace$  

</pre>

**Comment by IonicaBizau** [comment]
@SpaceG It's still there: https://github.com/SpaceG/gitlist.io/blob/master/package.json#L3

**Comment by SpaceG** [comment]
do i have remove it.? this  <code> "private": true, </code>

**Comment by IonicaBizau** [comment]
Yes, remove it and then `npm publish`.

**Comment by SpaceG** [comment]
Thanks much Ionica, i can learning alot. really.! -  i gonna change this one : 

You have to put your code here.

Change gitlist into lift, here. When you will run gitlist lift, the code from that callback will be executed.

I'm not sure how sails work, because I didn't work with it.

**Comment by IonicaBizau** [comment]
Great! Glad to hear! :grin:

**Comment by spacegits** [comment]
yes, need to fix alot of other things. hope we can run this app and made this a bigger.! 
let me know.

**Comment by spacegits** [comment]
how to include you in the https://www.npmjs.com/package/gitlist <https://www.npmjs.com/package/gitlist>
collaborators?

IMAO <-

**Comment by SpaceG** [comment]
hey Ionica. 

how npm publish again? 
<code> npm ERR! "You cannot publish over the previously published version 1.0.2." : gitlist
</code> 

thats mean i have to change the version? then right after i can go with <code> npm publish </code> again ... right ? 
<pre>
Space-Odysseys-Mac-Pro:gitlist.io cyberspace$ npm publish
npm ERR! publish Failed PUT 403
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "publish"
npm ERR! node v4.4.3
npm ERR! npm  v2.15.1
npm ERR! code E403

npm ERR! "You cannot publish over the previously published version 1.0.2." : gitlist
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/cyberspace/Documents/gitlist.io/npm-debug.log
Space-Odysseys-Mac-Pro:gitlist.io cyberspace$ 

</pre>

**Comment by IonicaBizau** [comment]
@SpaceG You have to bump the version.

**Comment by LibraryAV** [comment]
make the version higher?
right?

**Comment by SpaceG** [comment]
haha :D

**Comment by SpaceG** [comment]
it worked :D 👍  @IonicaBizau

**Comment by SpaceG** [comment]
this 

@SpaceG You have to put your code here.

Change gitlist into lift, here. When you will run gitlist lift, the code from that callback will be executed.

I'm not sure how sails work, because I didn't work with it.


does not lift the app.. its a blank page with the "Hello World" 


not the app... 
changed these steps which do you sait to me

https://github.com/SpaceG/gitlist.io/blob/master/cli.js

it not lift the app... hmg.. ?

**Comment by SpaceG** [comment]
this 

@IonicaBizau  You have to put your code here.

Change gitlist into lift, here. When you will run gitlist lift, the code from that callback will be executed.

I'm not sure how sails work, because I didn't work with it.


does not lift the app.. its a blank page with the "Hello World" 


not the app... 
changed these steps which do you sait to me

https://github.com/SpaceG/gitlist.io/blob/master/cli.js

it not lift the app... hmg.. ?

**Comment by SpaceG** [comment]
hey!.. please, this is your scriopt. tell me finally how to parse it.. that the people can lift the app... man, thats tilda thing is your script... and your part : 

/* color cli commandsline npm install cli-color
https://github.com/medikoo/cli-color
 */
/* tilda.js from Ionica Bizau
https://github.com/IonicaBizau/tilda
 */

var clc = require('cli-color');
var msg = clc.xterm(39).bgXterm(236);
console.log(msg('Welcome to Gitlist'));

parser.on("lift", action => {

        console.log("Start The GITLIST App");
        console.log("To see your app. visit:");
        console.log(clc.xterm(39).bgBlack.underline('http://127..0.0.1'));
        console.log("To Clone the Repository and Open Source:");
        console.log(clc.xterm(39).bgBlack.underline('http://www.github.com/spaceg/github.io'));

        console.log("©.2016 by Gitlist OS");
        console.log("press c to stop the app");


does not influnce of anything when i lift the app via sudo gitlist lift 

/* gitlist app
https://github.com/SpaceG/gitlist.io
 */


var http = require("http");
http.createServer(function(request, response) {
  response.writeHead(200, {"Content-Type": "text/plain"});
  response.write("Hello World");
  console.log("The Gitlist App reload the Site/Page")
  console.log("This is another console log.")


  response.end();
}).listen(80,"127.0.0.1");

just my code works...
and tell me finally.. howm to doing it. 
people want work on the source and can not wait.. !!!

or i want i back like sudo sails lift!

**Pull request merged**
